name: Publish Release
on:
  release:
    types: [published]
jobs:
  push_to_registry:
    name: Push Docker image to GitHub Packages
    runs-on: ubuntu-latest
    steps:
      - name: Login to Github Container Registry
        uses: docker/login-action@v1.8.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.PKG_PAT }}
      - name: Get Date of Build
        id: date
        uses: nanzm/get-time-action@v1.1
        with:
          timeZone: 0
          format: 'YYYY-MM-DD'
      - name: Set Release Version from Tag
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: main
      - name: Merge release tag to main
        uses: devmasx/merge-branch@v1.3.1
        with:
          type: now
          from_branch: dev
          target_branch: main
          github_token: ${{ github.token }}
      - name: Push to GitHub Packages
        uses: docker/build-push-action@v2.3.0
        with:
          tags: |
            ghcr.io/cloudera-labs/cdpctl:${{ env.RELEASE_VERSION }}
            ghcr.io/cloudera-labs/cdpctl:latest
          push: true
          build-args: |
            BUILD_DATE=${{ steps.date.outputs.time }}
            BUILD_TAG=${{ env.RELEASE_VERSION }}
            APPLICATION_VERSION=${{ env.RELEASE_VERSION }}
